### PR TITLE
Merge `styles.css` and `script.js` to `index.html`

### PR DESCRIPTION
**Pull request by jayantkageri**

### CODE REVIEW

**Comment by annihilatorrrr** [comment]
Ye particle js ka background image ka settings hai vro

**Comment by jayantkageri** [comment]
> Ye particle js ka background image ka settings hai vro

Usko `index.html` me merge kardia hai vro

**Comment by jayantkageri** [comment]
Now you can squash and merge, I have merged `styles.css` and `script.js` to `index.html` in `style` and `script` tag

**Comment by jayantkageri** [comment]
@annihilatorrrr you can now Squash and Merge, All the Warnings has been resolved

**Comment by annihilatorrrr** [comment]
> > Ye particle js ka background image ka settings hai vro
> 
> Usko `index.html` me merge kardia hai vro

Ok

**Pull request merged**
